name: interact with Github API
on:
  pull_request:

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: create short SHA
        id: short-sha
        run: echo 'sha_short=${GITHUB_SHA::7}' >> $GITHUB_OUTPUT
      - name: create issue
        id: create-issue
        run: |
          curl --request POST \
          --url https://api.github.com/repos/Mattias-Basle/tuto_github_actions/issues \
          --header 'authorization: Bearer ${{ secrets.API_GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Automated issue for commit: ${{ steps.short_sha.outputs.sha_short }}",
            "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ steps.short_sha.outputs.sha_short }}_."
            }' \
          --fail